### PR TITLE
docs: ✏️ added apple opensource projects docs

### PR DESCRIPTION
**Pull request by Sproff**
✅ #30

### CODE REVIEW

**Comment by saintmalik** [comment]
> ✅ #30

I also noticed something, you are creating your pull request straight from your main branch, thats a bad practice, you need to always create your own branch and send PRs from there, to avoid getting your PR closed or causing conflicts in the code base or repository next time.

**Comment by saintmalik** [comment]
> ✅ #30

Lastly, look at this documentation page that you added, https://swift.org/documentation/ , Visiting this page, you will notice that in the documentaion there isnt any quick way to make chnages like this Edit on GitHub button that is always at the button or a edit pen at the sidebar around the top corners.

How will beginners fiind the repo of this dicumentation so they can make contributions? by finding the repository of the documentation web pages.

So any documentation page that doesn't have the Edit button on their documentation web pages, its actually good for one to provide the GitHub Repository for them alongside.

Also looking at an Apple OSS Docs that you added https://github.com/apple/password-manager-resources, this OSS Project doesn't have a live documentation web page, that makes it invalid OSS Docs here.

Thanks once again

**Comment by saintmalik** [comment]
> ✅ #30

You added this [Zulip](https://github.com/zulip) - Powerful open source group chat. under Dropbox OSS Docs, but this happens to be an organisation that host alot of Projects entirely 👀.

**Comment by Sproff** [comment]
> > ✅ #30
> 
> You added this [Zulip](https://github.com/zulip) - Powerful open source group chat. under Dropbox OSS Docs, but this happens to be an organisation that host alot of Projects entirely 👀.

> > ✅ #30
> 
> I also noticed something, you are creating your pull request straight from your main branch, thats a bad practice, you need to always create your own branch and send PRs from there, to avoid getting your PR closed or causing conflicts in the code base or repository next time.

Noted, thanks.

**Pull request merged**
