### PR TITLE
Added More Active Netflix OSS

### PR DESCRIPTION
**Pull request by shazm12**
#### Summary
So I have added 2 new Open Source Projects by Netlfix which are on Big Data. I thank you for this opportunity and really appreciate what you all are doing.
Thank you!

#### Did you read the CONTRIBUTING.md?

Yes

#### Any relevant issues this PR addresses? (optional)
No

#70

### CODE REVIEW

**Comment by OSCA-Ado-Ekiti** [comment]
Thanks for the PR, but looking at the two OSS project you added.

Genie is active but doesn't have a docs page or folder.

Inviso is no longer active, as you can see last contribution was in 2017

**Comment by saintmalik** [comment]
Thanks for the PR, but looking at the two OSS project you added.

Genie is active but doesn't have a docs page or folder.

Inviso is no longer active, as you can see last contribution was in 2017

**Comment by shazm12** [comment]
okay thanks for informing and sorry my bad I ll check and try to find some recent open-source contribution projects.

**Comment by shazm12** [comment]
Hi @saintmalik , So I just did some more extensive research and have replaced the previous two projects with the new open Source Projects which have a docs page and are very active in terms of contributions.
Sorry for the inconvenience caused by me and I hope this will fit the criteria mentioned.
Thank you!

**Comment by saintmalik** [comment]
Thanks so much for your contribution 🙂👏

**Pull request merged**
